# Generated by Django 6.0.5 on 2026-05-29 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('cantidad_base', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bill of Material',
                'verbose_name_plural': 'Bill of Materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('IN_PROCESS', 'In Process'), ('FINISHED_GOOD', 'Finished Good')], max_length=20)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('unidad_medida', models.CharField(default='units', max_length=20)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre_maquina', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('capacidad_diaria', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desperdicio_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lista_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='manufacturing.billofmaterial')),
                ('materia_prima', models.ForeignKey(limit_choices_to={'tipo': 'RAW_MATERIAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='bom_details', to='manufacturing.product')),
            ],
            options={
                'verbose_name': 'BOM Detail',
                'verbose_name_plural': 'BOM Details',
            },
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='producto_terminado',
            field=models.ForeignKey(limit_choices_to={'tipo': 'FINISHED_GOOD'}, on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='manufacturing.product'),
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(max_length=50, unique=True)),
                ('cantidad_a_producir', models.PositiveIntegerField()),
                ('cantidad_producida', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('prioridad', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='manufacturing.product')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to=settings.AUTH_USER_MODEL)),
                ('centro_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='manufacturing.workcenter')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('ADJUSTMENT', 'Adjustment'), ('PRODUCTION_CONSUMPTION', 'Production Consumption'), ('PRODUCTION_INPUT', 'Production Input')], max_length=25)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField(blank=True, default='')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='manufacturing.product')),
                ('orden_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='manufacturing.productionorder')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('OPERARIO', 'Operario')], default='OPERARIO', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterial',
            unique_together={('producto_terminado', 'version')},
        ),
    ]
